version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      sentry:
        patterns:
          - "@sentry/*"
      react:
        patterns:
          - react
          - react-dom
          - react-router-dom
          - react-helmet-async
      types:
        patterns:
          - "@types/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
