// server.js
require('dotenv').config(); // Load environment variables
const express = require('express');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const compression = require('compression'); // Add compression for performance
const { fetchNewsData, fetchScheduleData, scrapeCHNStats } = require('./scraper'); // Import the news fetching function and new stats fetching function
const { saveToCache, getFromCache } = require('./src/scripts/caching-system');
const fs = require('fs').promises; // For reading roster/recruit data later
const path = require('path');

const app = express();
const port = process.env.PORT || 5000;
const isProduction = process.env.NODE_ENV === 'production';

// Performance: Enable gzip compression
app.use(compression());

// Path to the data file generated by scraper.py
const HOCKEY_DATA_PATH = path.join(__dirname, 'asu_hockey_data.json');

// Security: Add Helmet.js for security headers
app.use(helmet({
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"],
      styleSrc: ["'self'", "'unsafe-inline'"], // Allow inline styles for React
      scriptSrc: ["'self'"],
      imgSrc: ["'self'", "data:", "https:"], // Allow images from any HTTPS source
      connectSrc: ["'self'"],
    },
  },
  crossOriginEmbedderPolicy: false, // Disable for React compatibility
}));

// Security: Configure CORS with environment-based allowed origins
const allowedOrigins = process.env.CORS_ORIGINS
  ? process.env.CORS_ORIGINS.split(',').map(origin => origin.trim())
  : (isProduction
    ? [] // In production, require explicit configuration
    : ['http://localhost:3000', 'http://localhost:3001']); // Default to common dev ports

console.log('Allowed CORS origins:', allowedOrigins);

app.use((req, res, next) => {
  const origin = req.headers.origin;

  // Check if origin is in allowed list
  if (origin && allowedOrigins.includes(origin)) {
    res.header('Access-Control-Allow-Origin', origin);
  }

  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  res.header('Access-Control-Allow-Methods', 'GET, OPTIONS');

  // Handle preflight requests
  if (req.method === 'OPTIONS') {
    return res.sendStatus(200);
  }

  next();
});

// Security: Rate limiting for API endpoints
const apiLimiter = rateLimit({
  windowMs: parseInt(process.env.RATE_LIMIT_WINDOW_MS) || 15 * 60 * 1000, // 15 minutes default
  max: parseInt(process.env.RATE_LIMIT_MAX) || 100, // Limit each IP to 100 requests per windowMs
  message: 'Too many requests from this IP, please try again later.',
  standardHeaders: true, // Return rate limit info in the `RateLimit-*` headers
  legacyHeaders: false, // Disable the `X-RateLimit-*` headers
});

// Apply rate limiting to all API routes
app.use('/api/', apiLimiter);

app.get('/', (req, res) => {
  res.send('ASU Hockey Fan Site Backend');
});

// API endpoint for news
app.get('/api/news', async (req, res) => {
  try {
    const articlesArray = await fetchNewsData(); // fetchNewsData now returns an array of articles or an empty array on error

    if (articlesArray && articlesArray.length > 0) {
      // If articles are found, send them in the expected object structure
      res.json({
        data: articlesArray,
        source: 'api', // Simplified source, as fetchNewsData doesn't specify cache/live anymore
        timestamp: new Date().toISOString() // Add a current timestamp
      });
    } else {
      // If articlesArray is empty or null, it means no articles were found or an error occurred during scraping
      console.error('/api/news: No news data returned from fetchNewsData or an error occurred internally in scraper.');
      res.status(500).json({ error: 'Failed to fetch news data or no news available.' });
    }
  } catch (error) {
    // This catch block handles unexpected errors in the endpoint logic itself
    console.error('Error in /api/news endpoint:', error);
    res.status(500).json({ error: 'Internal server error while fetching news.' });
  }
});

// API endpoint for schedule data
app.get('/api/schedule', async (req, res) => {
  try {
    const scheduleDataArray = await fetchScheduleData(); // fetchScheduleData now returns an array of games or an empty array on error

    if (scheduleDataArray && scheduleDataArray.length > 0) {
      res.json({
        data: scheduleDataArray,
        source: 'api', // Simplified source
        timestamp: new Date().toISOString()
      });
    } else {
      console.error('/api/schedule: No schedule data returned from fetchScheduleData or an error occurred internally in scraper.');
      res.status(500).json({ error: 'Failed to fetch schedule data or no schedule available.' });
    }
  } catch (error) {
    console.error('Error in /api/schedule endpoint:', error);
    res.status(500).json({ error: 'Internal server error while fetching schedule data.' });
  }
});

// Helper function to read and parse the hockey data JSON file
async function getHockeyData() {
  try {
    const rawData = await fs.readFile(HOCKEY_DATA_PATH, 'utf8');
    return JSON.parse(rawData);
  } catch (error) {
    if (error.code === 'ENOENT') {
      console.error('Error: asu_hockey_data.json not found.');
      return null; // Or throw new Error('Data file not found') if you want to ensure it always exists
    }
    console.error('Error reading or parsing asu_hockey_data.json:', error);
    return null; // Or throw error
  }
}

// API endpoint for roster data
// API endpoint for roster data
// API endpoint for roster data
app.get('/api/roster', async (req, res) => {
  try {
    const hockeyData = await getHockeyData();
    let roster = hockeyData ? (hockeyData.roster || []) : [];

    // Merge live roster data (full details)
    try {
      // Import on demand or move top-level if preferred, but for now we need the new export
      const { scrapeCHNRoster } = require('./scraper');
      console.log('[Roster API] Fetching live CHN roster for sync...');
      const liveRoster = await scrapeCHNRoster();
      console.log(`[Roster API] Scraped ${liveRoster.length} players from CHN.`);

      // Create a map of existing players for easier lookup by name
      const existingMap = new Map();
      roster.forEach(p => {
        const cleanName = p.name.replace(/\s*\([A-Z]+\)\s*/i, '').trim().toLowerCase();
        existingMap.set(cleanName, p);
      });

      liveRoster.forEach(p => {
        // CHN keys: #, Player, Yr, Pos, S/C, Ht, Wt, DOB, Hometown, Last Team
        let rawName = p.Player;
        if (!rawName) return;

        // Clean name (sometimes has trailing spaces or chars)
        let name = rawName.trim();
        const lowerName = name.toLowerCase();

        // Calculate nationality from hometown
        const hometown = p.Hometown || '';
        const nationality = determineNationality(hometown);

        // Check if existing
        if (existingMap.has(lowerName)) {
          // Update existing player if fields are missing
          const existingPlayer = existingMap.get(lowerName);

          if (!existingPlayer.number || existingPlayer.number === '-' || existingPlayer.number === '') {
            existingPlayer.number = p['#'] || existingPlayer.number;
          }
          if (!existingPlayer.height || existingPlayer.height === '-' || existingPlayer.height === '') {
            existingPlayer.height = p.Ht || existingPlayer.height;
          }
          if (!existingPlayer.weight || existingPlayer.weight === '-' || existingPlayer.weight === '') {
            existingPlayer.weight = p.Wt || existingPlayer.weight;
          }
          if (!existingPlayer.born || existingPlayer.born === '-' || existingPlayer.born === '') {
            existingPlayer.born = p.DOB || existingPlayer.born;
          }
          if (!existingPlayer.birthplace || existingPlayer.birthplace === '-' || existingPlayer.birthplace === '') {
            existingPlayer.birthplace = p.Hometown || existingPlayer.birthplace;
          }
          if (!existingPlayer.shoots || existingPlayer.shoots === '-' || existingPlayer.shoots === '' || !existingPlayer.shoots) {
            existingPlayer.shoots = p['S/C'] || existingPlayer.shoots || '-';
          }

          // Always update/set nationality if we derived it and it's missing or default
          if (!existingPlayer.nationality || existingPlayer.nationality === 'USA') {
            existingPlayer.nationality = nationality;
          }

        } else {
          console.log(`[Roster API] Adding missing player with details: ${name}`);

          // Format Name (Pos)
          let pos = p.Pos || '';
          let displayName = pos ? `${name} (${pos})` : name;

          const newPlayer = {
            number: p['#'] || '',
            name: displayName,
            position: pos,
            height: p.Ht || '-',
            weight: p.Wt || '-',
            shoots: p['S/C'] || '-', // Shoots/Catches
            born: p.DOB || '-',
            birthplace: p.Hometown || '-',
            nationality: nationality,
            player_link: ''
          };
          roster.push(newPlayer);
          // Add to map to prevent duplicates if CHN lists twice (unlikely)
          existingMap.set(lowerName, newPlayer);
        }
      });

      // Final pass: Ensure everyone has a link
      roster.forEach(p => {
        if (!p.player_link) {
          // Generate Elite Prospects search link
          // Remove (G), (D), (F) from name for search
          const cleanName = p.name.replace(/\s*\([A-Z]+\)\s*/i, '').trim();
          p.player_link = `https://www.eliteprospects.com/search/player?q=${encodeURIComponent(cleanName)}`;
        }
      });

    } catch (mergeError) {
      console.error('[Roster API] Error merging live roster data:', mergeError);
    }




    if (roster.length > 0) {
      res.json(roster);
    } else {
      res.status(404).json({ error: 'Roster data not found.' });
    }
  } catch (error) {
    console.error('Error in /api/roster:', error);
    res.status(500).json({ error: 'Internal server error while fetching roster data.' });
  }
});

// API endpoint for recruiting data
app.get('/api/recruits', async (req, res) => {
  try {
    const hockeyData = await getHockeyData();
    if (hockeyData && hockeyData.recruiting) {
      res.json(hockeyData.recruiting);
    } else {
      res.status(404).json({ error: 'Recruiting data not found or file is invalid.' });
    }
  } catch (error) {
    console.error('Error in /api/recruits:', error);
    res.status(500).json({ error: 'Internal server error while fetching recruiting data.' });
  }
});


function determineNationality(hometown) {
  if (!hometown || hometown === '-') return 'USA';
  const h = hometown.toUpperCase();

  // European/International codes
  const europeMap = {
    'SVK': 'SVK', 'SLOVAKIA': 'SVK',
    'CZE': 'CZE', 'CZECH': 'CZE',
    'SWE': 'SWE', 'SWEDEN': 'SWE',
    'FIN': 'FIN', 'FINLAND': 'FIN',
    'RUS': 'RUS', 'RUSSIA': 'RUS',
    'GER': 'GER', 'GERMANY': 'GER',
    'LAT': 'LAT', 'LATVIA': 'LAT',
    'BLR': 'BLR', 'BELARUS': 'BLR',
    'SUI': 'SUI', 'SWITZERLAND': 'SUI',
    'AUT': 'AUT', 'AUSTRIA': 'AUT',
    'GBR': 'GBR', 'UK': 'GBR'
  };

  for (const [key, code] of Object.entries(europeMap)) {
    if (h.includes(key)) return code;
  }

  // Canada detection
  // Check for "CAN", "CANADA", or common province abbreviations/names found in hockey databases
  // Note: " AB" (Alberta), " BC" (British Columbia), " ON" (Ontario), etc.
  // Using spaces to avoid matching inside words (e.g. "CANT")
  // Also matching "ONT.", "MAN.", "ALB.", "SASK." based on screenshot
  if (h.includes('CAN') || h.includes('CANADA') ||
    h.includes(' ON') || h.includes('QUE') || h.includes(' BC') || h.includes(' AB') || h.includes(' MB') ||
    h.includes(' SK') || h.includes(' NS') || h.includes(' NB') || h.includes(' PE') || h.includes(' NL') ||
    h.includes('ONT') || h.includes('MAN') || h.includes('ALB') || h.includes('SASK')) {
    return 'CAN';
  }

  // Default to USA
  return 'USA';
}

app.get('/api/stats', async (req, res) => {
  // Include season in cache key to avoid conflicts between seasons
  const config = require('./config/scraper-config');
  const statsSeason = config.seasons.stats;
  const cacheKey = `chn_stats_${statsSeason}`;

  try {
    const cachedData = await getFromCache(cacheKey);
    if (cachedData) {
      console.log(`[Cache System] Stats data found in cache for ${cacheKey}.`);
      return res.json(cachedData);
    }

    console.log(`[Cache System] No cache found for ${cacheKey}. Scraping live data.`);
    const statsData = await scrapeCHNStats();
    if (statsData.skaters.length > 0 || statsData.goalies.length > 0) {
      await saveToCache(statsData, cacheKey);
      res.json(statsData);
    } else {
      res.status(500).json({ error: 'Failed to fetch stats data.' });
    }
  } catch (error) {
    console.error('Error in /api/stats endpoint:', error);
    res.status(500).json({ error: 'Internal server error while fetching stats.' });
  }
});

// Serve the React application's static files from the 'build' directory
app.use(express.static(path.join(__dirname, 'build')));

// For any other request, serve the React app's index.html file
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'build', 'index.html'));
});

app.listen(port, () => {
  console.log(`\n🚀 ASU Hockey Website Server`);
  console.log(`================================`);
  console.log(`Environment: ${isProduction ? 'PRODUCTION' : 'DEVELOPMENT'}`);
  console.log(`Server: http://localhost:${port}`);
  console.log(`\nAPI Endpoints:`);
  console.log(`  News:      http://localhost:${port}/api/news`);
  console.log(`  Roster:    http://localhost:${port}/api/roster`);
  console.log(`  Recruits:  http://localhost:${port}/api/recruits`);
  console.log(`  Schedule:  http://localhost:${port}/api/schedule`);
  console.log(`  Stats:     http://localhost:${port}/api/stats`);
  console.log(`================================\n`);
});
